### ISSUE TITLE
Problems with version 4.9.0

### ISSUE THREAD

**Issue by vaulot** [vaulot/pr2_database#5]
Dear Daniel,
 
I hope you are well. I am currently analyzing a number of 18S MiSeq datasets with the software mothur (v. 1.39.5) and am using the PR2 database for the classification of sequences and OTUs. I have used PR2 version 4.7.2 for mothur in the past and found the classification much better in comparison to SILVA NR v. 132 – as was to be expected. 😊 I now tried to use the new version PR2 v. 4.9.0 for mothur but unfortunately encountered some errors that in the end cause mothur to abort. I checked the error messages I got by simply opening the fasta and tax files in Notepad and found that it was mainly formatting errors that caused the problems. I think/hope that these can easily be fixed.
 
FJ402948.1.1186_U & FJ402949.1.1210_U are both found twice in the tax file. As mothur requires each file to be unique, these doublets cause an error.
 
“LC054937.1.1751_U is missing the final ';', ignoring. [ERROR]: ;Plagiodinium;Plagiodinium_belizeanum; is missing the final ';', ignoring.”
The sequence LC054937.1.1751_U has an accidental hard return after the name Prorocentraceae, therefore mothur does not recognize that the ; and the final part of the taxonomy (“;Plagiodinium;Plagiodinium_belizeanum;”) belong together.
 
“'AB353770.1.1740_U' is in your template file and is not in your taxonomy file. Please correct.”
This error is shown for each sequence in the PR2 database and it is what cause mothur to abort. I think that this has to do with incorrect hard returns and TABs in the new version. If I look at v 4.7.2 using NotePad, the fasta file looks like
 
>AB353770.1.1740_U
ATGCTTGTCTCAAAGATTAAGCCATGCATGTCTCAGTATAAGC…
>KC672520.1.1801_U
TACCTGGTTGATTCTGCCCCTATTCATATGCTTGTCTCAAAGATTAAGCC…
 
And in the taxonomy file the lines are all like
 
AB353770.1.1740_U           Eukaryota;Alveolata;Dinophyta;Dinophyceae;Dinophyceae_X;Dinophyceae_XX;Peridiniopsis;Peridiniopsis_kevei;
KC672520.1.1801_U      Eukaryota;Opisthokonta;Fungi;Ascomycota;Pezizomycotina;Leotiomycetes;Leotiomycetes_X;Leotiomycetes_X_sp.;
 
In version 4.9.0 the fasta file looks like
 
>AB353770.1.1740_UATGCTTGTCTCAAAGATTAAGCCATGCATGTCTCAGTATAAGC…>KC672520.1.1801_UTACCTGGTTGATTCTGCCCCTATTCATATGCTTGTCTCAAAGATTAAGCC…
 
Similarly, the tax file looks like
 
AB353770.1.1740_U Eukaryota;Alveolata;Dinoflagellata;Dinophyceae;Peridiniales;Kryptoperidiniaceae;Unruhdinium;Unruhdinium_kevei;KC672520.1.1801_U Eukaryota;Opisthokonta;Fungi;Ascomycota;Pezizomycotina;Leotiomycetes;Leotiomycetes_X;Leotiomycetes_X_sp.;AB284159.1.1765_U Eukaryota;Alveolata;Dinoflagellata;Dinophyceae;Peridiniales;Protoperidiniaceae;Protoperidinium;Protoperidinium_bipes;AY123745.1.924_UC                …
 
I assume that these formatting errors cause the mothur software to not recognize the corresponding names in the fasta and tax files.

René Groben

**Comment by vaulot** [comment]
Dear René

I localized the first three errors and fixed them. in the latest release 4.9.1. 

Concerning the last error, this is due to the fact the text files are in UNIX format so there is just a LF character at the end of each line. What you should do use Notepad++ or similar to convert the end of lines characters for both fasta and .  I have explained this in the wiki, [here (see at the end): ](https://github.com/vaulot/pr2_database/wiki/PR2-files)

Please let me know if this works for you now.

Cheers.  Daniel

**Comment by rgroben** [comment]
Dear Daniel,

thank you for the quick response and your help! There were however a few more errors that popped up when I tried to use v. 4.9.1. I fixed them in my version of the files but want to mention them here as well so that they can be "officially" corrected (see below). Also, after some problems in the beginning, I realized that the format in which to save the files in Notepad++ is very important. mothur is very sensitive regarding correct text file types. Saving it as a *.txt file (the default setting in Notepad++) adds specific formatting information to the file which will stop mothur from properly recognizing it as e.g. a *.tax file anymore. 

But in the end everything worked well and I could classify my sequences with the latest version of PR2.

Errors in file “pr2_version_4.9.1_mothur.fasta”
KJ995958.1.1684_U contains a space between > and KJ995958.1.1684_U; delete space

Errors in file “pr2_version_4.9.1_mothur.tax”
LC002840.1.1722_U contains a hard break in its taxonomic classification; delete hard space
KJ995958.1.1684_U contains a space before  KJ995958.1.1684_U; delete space

The Wiki explanation for “Converting files from UNIX to Windows format” should to be amended with this following instruction at “4. Save the files”:
Save files using “Save as” and change “Save as type” from “Normal text file (*.txt)” to “All types (*.*)”.

Best wishes and thanks to everyone involved in the creation of PR2 for your great work,

René

**Comment by vaulot** [comment]
Dear René

Thanks very much for your feed back.  This is very important for PR2 so that we can have a really clean database.  
For Notepad++ I just open the file and save it without modifying anything. I think saving as txt does not change anything in the file itself but it add the "txt" extension which then you have to add in the mothur command.  But I will add this in the wiki.  
I have fixed the two remaining errors and just done a new release 4.9.2.
